---

redis_version: "3.2.0"
nginx_version: "1.10.0"
php_version: "7.0.7"
es_version: "2.3.3"
user: "adam"
group: "adam"
download_host: "http://adam.link4age.com:9000/resource/"

server_name: "*.linkagegame.com"
document_root: "/app"
base_dir: "/opt/nginx-{{ nginx_version }}"
fpm_port: 9001
app_php_path: "/app"

es_data_dir: "/data/es"
es_hosts: ["172.31.31.161", "172.31.31.162"]

chat_port: 1900
proxy_port: 1800
proxy_host1: "192.168.1.6:6000"
proxy_host2: "192.168.1.6:6100"
chat_host1: "192.168.1.6:4000"
chat_host2: "192.168.1.6:4100"

mysql_data_dir: "/data/mysql"
mysql_base_dir: "{{ mysql_data_dir }}"
mysql_root_pass: "link@ge160525"
mysql_developer_pass: "p@ssword!linkage"
mysql_backup_pass: "link@gesync16"
mysql_master_port: 3401
mysql_slave_port: [3402, 3403]