- mysql_user: login_port=3401 login_user=root login_password={{ mysql_root_pass }} login_unix_socket={{ mysql_data_dir }}/socket/mysql-3401.sock name=backup host="%" password="{{ mysql_backup_pass }}" priv="*.*:REPLICATION SLAVE" state=present
- name: Get the current master servers replication status
  mysql_replication: login_port=3401 login_user=root login_password={{ mysql_root_pass }} login_unix_socket={{ mysql_data_dir }}/socket/mysql-3401.sock mode=getmaster
  register: repl_stat

- name: Change the master in slave to start the replication
  shell: mysql -uroot -P{{ item }} -p{{ mysql_root_pass }} -S {{ mysql_data_dir }}/socket/mysql-{{ item }}.sock -e "change master to master_host='127.0.0.1',master_port=3401,master_log_file='{{ repl_stat.File }}',master_log_pos={{ repl_stat.Position }},master_user='backup',master_password='{{ mysql_backup_pass }}'"
  with_items: 
    - [3402, 3403]
  ignore_errors: True